export const ADMIN_SERVICE = 'DANIMAI_ADMIN_SERVICE';
export const ADMIN_CONFIG = 'DANIMAI_ADMIN_CONFIG';
export const APP_ENTITIES = 'DANIMAI_APP_ENTITIES';
export const ADMIN_DATASOURCE = 'DANIMAI_ADMIN_DATASOURCE';
