export const FEAUTURE_NAME_METADATA = 'DANIMAI_FEAUTURE_NAME_METADATA';
export const ACTION_NAME_METADATA = 'DANIMAI_ACTION_NAME_METADATA';
export const OVERRIDE_METHOD_METADATA = 'DANIMAI_OVERRIDE_METHOD_METADATA';
export const PARSED_BODY_METADATA = 'DANIMAI_PARSED_BODY_METADATA';
export const PARSED_CRUD_REQUEST_KEY = 'DANIMAI_PARSED_CRUD_REQUEST_KEY';
export const CRUD_OPTIONS_METADATA = 'DANIMAI_CRUD_OPTIONS_METADATA';
